In [ ]:
''' 
Phân tích suy diễn (inferrential statistics) 
Lý do tại sao cần suy diễn: Kết luận dựa trên dữ liệu sample (mẫu) nhưng kết luận thì 
được hiểu là áp dụng cho tổng thể 
Câu hỏi đặt ra: Kết luận trên mẫu đó có phù hợp với tổng thể hay không 
Khi phân tích suy diễn cần lưu ý: 
1. Xác định giả thuyết H0 
2. Các giả định hay các điều kiện về dữ liệu và môi trường để áp dụng kiểm điểm  - Lưu ý về giả định phân phối của biến số: normal, student, poison, chi-square... 
3. Thiết lập mức tin cậy và sai lầm (alpha): 90% - 10%, 95% - 5% và 99% - 1% 
4. Quy tắc suy diễn:  
4.1 Nếu p-value < alpha => reject H0 
4.2 Nếu p-value > alpha => accecpt H0 
5. Kết luận của suy diễn chỉ cho chúng ta biết là có đủ dữ kiện để kết luận cho tổng thể 
hay không (còn gọi là ý nghĩa thống kê) 
'''

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
#Đọc File dulieutuyensinh 
df = pd.read_csv('dulieuxettuyendaihoc.csv',header=0,delimiter=',',encoding='utf8')

In [2]:
#Đổi tên cột 
df = df 
[['T5','T6','GT','DT','KV','KT','NGONNGU','TOANLOGICPHANTICH','GIAIQUYETVANDE','NGAYTHI','DINHHUONGNGHENGHIEP']] 
df.rename(columns={'TOANLOGICPHANTICH':'LOGIC','GIAIQUYETVANDE':'UNGXU', 
'DINHHUONGNGHENGHIEP':'HUONGNGHIEP'},inplace=True)

In [3]:
'''
ONE SAMPLE T-TEST 
Mục đích: Kiểm định trung bình của 1 biến số (định lượng) co bằng một giá trị 
n < 30 
''' 
# H0: mean = X 
import scipy.stats as stats

In [4]:
# câu 1: Hãy kiểm ta xem LOGIC thí sinh khối C có bằng 4.0 
dfKhoiC = df.loc[df['KT'] == 'C'] 
dfKhoiC['LOGIC']

1     4.00
2     6.75
6     6.75
22    3.50
23    5.25
24    2.25
25    2.00
26    4.50
27    5.00
95    1.50
96    3.75
97    8.00
98    3.50
99    2.50
Name: LOGIC, dtype: float64

In [5]:
# Với one sample T-test thì giả thiết G0: muy = 4.0 
# Mặc định mức tin cậy là 95% và mức sai lầm là 5% 
stats.ttest_1samp(dfKhoiC['LOGIC'],popmean=4.0) 
# Kết luận: 
# Do alpha = 0.05 và p-value = 0.66... 
# Suy ra đủ dữ liệu để nói rằng trung bình môn thi LOGIC bằng 4.0 
# hay nói cách khác là chấ nhận H0 ở mức sai lầm 5%

TtestResult(statistic=0.44599723713991907, pvalue=0.6629370899710998, df=13)

In [6]:
# Điểm trung bình có môn thi UNGXU của khối thi C có bằng 5.0 hay không 
stats.ttest_1samp(dfKhoiC['UNGXU'],popmean=5) 
# KẾt luận :  
# do anpha = 0.05 và p-value =0.4581953822944209 
# Suy ra đủ dữ liệu để nói rằn trung bình môn thi UNGXU = 5.0 
# hay nói cách khác là châp nhận G0 ở mức sai lầmm 5%

TtestResult(statistic=-0.7645471693105148, pvalue=0.4581953822944209, df=13)

In [7]:
# Tự nghiên cứu cách thiết lập mức tin cậy hoặc sai lầm trong đoạn code trên
# Bài tập tương tự: HÃy kiểm tra xem có phải điểm NGONNGU của thí sinh thi khối C 
# là 5.5 hay không với mức sai lầm là 10%
# TWO SAMPLE T-TEST 
stats.ttest_1samp(dfKhoiC['NGONNGU'],popmean=5.5)
# Mục đích: Kiểm tra xem trung bình của 2 biến số (định lượng)có bằng nhau không 
#The sample size < 30 
#H0 :delta_mean = 0

#Ket luan: 
# Do alpha = 0.1 va p-value = 0.47223461312805337
# Suy ra du du lieu de noi rang trung binh cua 2 bien so NGONNGU = 5.5
# hay noi cach khac la chap nhan H0 o muc sai lam 10%

TtestResult(statistic=0.7403728818402906, pvalue=0.47223461312805337, df=13)

In [8]:
# Câu 2: Kiểm tra xem trung bình điểm thi LOGIC và trung bình điểm thi UNGXU của 
# thí sinh thi khối C có bằng nhau không 
# H0: mean_LOGIC - mean_UNGXU = 0 
dfKhoiC = df.loc[df['KT'] == 'C'] 
stats.ttest_ind(dfKhoiC['LOGIC'],dfKhoiC['UNGXU'],equal_var=True)
# Kết luận: Do alpha = 0.0.5 và p-value = 0.3111543826061086 
# Suy ra đủ dữ liệu để nói rằng trung bình LOGIC bằng trung bình UNGXU hay nói cách 
# khác là chấp nhận H0 ở mức sai lầm 5%

TtestResult(statistic=-1.0329196014245297, pvalue=0.3111543826061086, df=26.0)

In [9]:
# Kiểm tra xem trung bình 3 UNGXU có bằng trung bình NGONNGU cho thí sinh thi 
# khối C hay không với mức tin cậy 99%

stats.ttest_ind(dfKhoiC['UNGXU'],dfKhoiC['NGONNGU'],equal_var=True)

# Kết luận: Do alpha = 0.01 và p-value = 0.014085909192033959
# Suy ra đủ dữ liệu để nói rằng trung bình UNGXU không bằng trung bình NGONNGU
# hay nói cách khác là reject H0 ở mức sai lầm 1%
# ONE SAMPLE Z-TEST 
# Mục đích: kiểm định trung bình của một biến số (định lượng) 
# H0L mean = x 
# n > 30

TtestResult(statistic=-2.6321295849540447, pvalue=0.014085909192033959, df=26.0)

In [10]:
from statsmodels.stats.weightstats import ztest as ztest

In [11]:
# Hãy kiểm tra xem trung bình điểm toán học kì 2 lớp 12 có bằng 8.0 
ztest(df['T6'],value=8.0) 
# Kết luận: điểm trung bình không bằng 8 
# TWO SAMPLE Z-TEST 
# Tương tự n > 30 
# H0: u1 = u2 both population means are equal

(-7.797828845339864, 6.298135014120743e-15)

In [12]:
# Câu 4: Hãy kiểm tra xem điểm trung bình toán học kì 1 và học kì 2 năm lớp 12 có bằng 
# nhau không 
ztest(df['T5'],df['T6'],value=0)
# Đủ dữ kiện kết luận trung bình 2 học kì có bằng nhau

(-1.094138573502891, 0.273894207026412)

In [13]:
# Tương tự kiểm tra trung bình LOGIC và UNGXU có bằng nhau không 
ztest(df['LOGIC'],df['UNGXU'],value=0)
#  Nhỏ hơn => bác bỏ

(-4.172765180703833, 3.009250404643791e-05)

In [14]:
# Tương tự kiểm tra trung bình LOGIC và UNGXU có bằng nhau không với mức tin cậy 
# 95%
ztest(df['LOGIC'],df['UNGXU'],value=0,alternative='two-sided')
# Kết luận: Đủ dữ liệu để bác bỏ giả thiết H0

(-4.172765180703833, 3.009250404643791e-05)

In [15]:
''' 
# Kiểm định tương quan giữa 2 biến định lượng 
# H0: r = 0 
''' 
from scipy.stats.stats import pearsonr

C:\Users\Admin\AppData\Local\Temp\ipykernel_5144\2168582929.py:5: DeprecationWarning: Please import `pearsonr` from the `scipy.stats` namespace; the `scipy.stats.stats` namespace is deprecated and will be removed in SciPy 2.0.0.
  from scipy.stats.stats import pearsonr

In [16]:
# Câu 5: Kiểm tra xem điểm toán hk1 và hk2 năm lớp 12 có tương quan không 
pearsonr(df['T5'],df['T6'])
# Bác bỏ giả thiết H0 : r = 0 do p-value < 0.05 => r != 0 => 2 biến không tương quan
# (pvalue thì tương quan trên tổng thể, và không cho biết tương quan thuận hay nghịch)
# statistic là giá trị tương quan trên mẫu, nhìn lên sẽ biết tương quan mạnh hay sao
# Kết luận: đủ dữ liệu để nói rằng T5 và T6 có tương quan với nhau với mức tin cậy 95%

PearsonRResult(statistic=0.7786831657869809, pvalue=1.4846407216273482e-21)

In [ ]:
''' 
Kết luận trên mẫu: tương quan thuận, mức độ tương quan rất cao: r = 
0.7786831657869809 
Suy diễn trên tổng thể: Đủ dữ liệu để nói rằng T5 và T6 có tương quan với nhau với mức 
sai lầm là 5% 
Với p-value = 1.4846407216273482e 
''' 
''' 
Định tính: Fisher (<30) 
Chi square (>30) 
Cả 2 H0: độc lập  
''' 
''' 
Định lượng: 
one sample t-test và one sample z-test => biến định lượng (H0; muy = alpha) 
two sample t-test và two sample z-test => kiểm tra 2 biến định lượng có bằng nhau không 
(H0: denta muy = 0) 
kiểm định Pearson kiểm tra xem 2 biến định lượng có tương quan không (H0: n=0) 
'''

In [17]:
# Sinh viên làm tương tự cho T5 và LOGIC có tương quan hay không 
pearsonr(df['T5'],df['LOGIC']) 
# statis: quá thấp còn pvalue > 0.05 nên chấp nhận H0 => 2 biến không tương quan

PearsonRResult(statistic=0.18464661226012727, pvalue=0.06590059130545516)

In [ ]:
# Fisher Test 
# Mục đích: Kiểm tra sự độc lập của 2 biến định tính dạng nhị phân 2x2
# Ho: Không có sự khác biệt giữa 2 biến định tính 
import scipy.stats as stats

In [18]:
# Hãy kiểm tra xem có sự phụ thuộc nào giữa việc sinh viên có định hướng nghề nghiệp 
# và giới tính khi thí sinh đăng ký dự thi hay không 
crosdata = pd.crosstab(df['GT'],[df['HUONGNGHIEP']],rownames=['GT'],colnames=['HUONGNGHIEP']) 
odd_ratio, p_value = stats.fisher_exact(crosdata) 
print('odd ratio is: ' + str(odd_ratio)) 
print('p_value is: ' + str(p_value)) 
# Kết luận: p_value = 0.22763927303454412 > 0.05 => chấp nhận H0 => không có sự phụ thuộc
# Tức là đủ dữ liệu để nói rằng không có sự phụ thuộc giữa việc sinh viên có định hướng ở mức sai lầm 5%

odd ratio is: 0.575
p_value is: 0.22763927303454412

In [19]:
# Chi-Square Test 
# Mục đích: Kiểm tra sự độc lập của 2 biến định tính 
# Ho: Không có sự khác biệt giữa 2 biến định tính 
from scipy.stats import chi2_contingency

In [21]:
# Hãy kiểm tra xem có sự phụ thuôc nào giữa khối thi và khu vực thi đăng ký dự thi hay 
# không 
crosdata = pd.crosstab(df['KV'],[df['KT']],rownames=['KV'],colnames=['KT']) 
crosdata 
stat, p, dof, ex = chi2_contingency(crosdata)
# interpret p-value 
alpha = 0.05 
print("p value is " + str(p)) 
if p <= alpha: 
    print ('Dependent (Reject H0)') 
else: 
    print ('Independent (H0 holds true)') 
# Kết luận: p-value = 0.02012461887796485 < 0.05 => reject H0 => có sự phụ thuộc giữa khối thi và khu vực thi
# Tức là đủ dữ liệu để nói rằng có sự phụ thuộc giữa khối thi và khu vực thi ở mức sai lầm 5%

p value is 0.02012461887796485
Dependent (Reject H0)

In [22]:
# GT và KT có mối quan hệ hay không 
crosdata = pd.crosstab(df['GT'],[df['KT']],rownames=['GT'],colnames=['KT'])
stat, p, dof, ex = chi2_contingency(crosdata)
# interpret p-value
alpha = 0.05
print("p value is " + str(p))
if p <= alpha:
    print ('Dependent (Reject H0)')
else:
    print ('Independent (H0 holds true)')
# Kết luận: p-value = 0.005044752209452435 < 0.05 => reject H0 => có sự phụ thuộc giữa giới tính và khối thi
# Tức là đủ dữ liệu để nói rằng có sự phụ thuộc giữa giới tính và khối thi ở mức sai lầm 5%

p value is 0.005044752209452435
Dependent (Reject H0)

In [ ]:
# ONE WAY ANOVA 
# Kiểm định ANOVA ONE WAY 
# Yêu cầu: 
# 1. Biến định lượng trên nhóm định tính 
# 2. Các biến định lượng trên từng nhóm theo phân phối chuẩn 
# 3. H0: Giá trị trung bình dữ liệu định lượng trên từng nhóm định tính là bằng nhau

In [23]:
# Điểm toán học kì 2 lớp 12 có phụ thuộc vào giới tính hay không
import statsmodels.api as sm
from statsmodels.formula.api import ols

model = ols('T6 ~ GT',data=df).fit()
anova_table = sm.stats.anova_lm(model,typ=1)
anova_table
# Kết luận: p-value = 0.363426 > 0.05 => chấp nhận H0 => không có sự phụ thuộc giữa điểm toán và giới tính

            df     sum_sq  mean_sq         F    PR(>F)
GT         1.0    1.55201  1.55201  0.833769  0.363426
Residual  98.0  182.42109  1.86144       NaN       NaN

In [24]:
# Điểm LOGIC có phụ thuộc vào KV hay không
model = ols('LOGIC ~ KV',data=df).fit()
anova_table = sm.stats.anova_lm(model,typ=1)
anova_table
# Kết luận: p-value = 0.066299 < 0.05 => reject H0 => có sự phụ thuộc giữa đi

            df      sum_sq   mean_sq         F    PR(>F)
KV         2.0    6.053398  3.026699  2.790934  0.066299
Residual  97.0  105.194102  1.084475       NaN       NaN

In [25]:
# Điểm UNGXU có phụ thuộc khối thi hay không 
model = ols('UNGXU ~ KT',data=df).fit()
anova_table = sm.stats.anova_lm(model,typ=1)
anova_table
# Kết luận: p-value = 0.46041 < 0.05 => reject H0 => có sự phụ thuộc giữa điểm UNGXU và khối thi

            df      sum_sq   mean_sq         F   PR(>F)
KT         4.0    3.967636  0.991909  0.911814  0.46041
Residual  95.0  103.344864  1.087841       NaN      NaN

In [ ]:
''' 
Two way anova  
# Kiểm định ANOVA two WAY 
# Yêu cầu: 
# 1. Biến định lượng trên nhóm định tính
# 2. Các biến định lượng trên từng nhóm theo phân phối chuẩn 
# 3. H0: Trung bình các cột dữ liệu bằng nhau 
'''

In [26]:
# Hãy cho biết điểm LOGIC có phụ thuộc vào loại GT trên từng nhóm KV hay không 
# Performing two-way anova 
model = ols('LOGIC ~ GT + KV + GT:KV',data=df).fit()
result = sm.stats.anova_lm(model,typ=2)
result
# Kết luận: p-value = 0.576510 > 0.05 => chấp nhận H0 
# Bác bỏ H0 => có sự phụ thuộc pvalue = 0.019173
# GT:KV bác bỏ -> không có sự phụ thuộc giữa GT và KV -> tuy nhiên điểm LOGIC trên từng nhóm GT xét theo từng KV nừa thì nó độc lập với nhau
''' 
Kết luận khác  
p-value = 0.052602 -> LOGIC độc lập theo nhóm GT 
p-value = 0.0.019173 -> LOGIC phụ thuộc theo nhóm KV 
p-value = 0.576510 -> LOGIC độc lập theo nhóm GT trên từng loại KV 
'''

             sum_sq    df         F    PR(>F)
GT         6.506318   1.0  6.270309  0.014001
KV         8.561314   2.0  4.125382  0.019173
GT:KV      1.149707   2.0  0.554002  0.576510
Residual  97.538077  94.0       NaN       NaN

In [27]:
# Phân tích xem NGONNGU có phụ thuộc theo nhóm KV trên từng nhóm KT hay không 
model = ols('NGONNGU ~ KV + KT + KV:KT',data=df).fit()
result = sm.stats.anova_lm(model,typ=2)
result
# Kết luận: Tất cả đều phụ thuộc vào nhau

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsmodels\base\model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 4, but rank is 2
  warnings.warn('covariance of constraints does not have full '
C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsmodels\base\model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 8, but rank is 6
  warnings.warn('covariance of constraints does not have full '

              sum_sq    df          F    PR(>F)
KV          2.423830   2.0   0.809994  0.448187
KT         88.176672   4.0  14.733410  0.000003
KV:KT       1.369256   8.0   0.114394  0.994507
Residual  130.169640  87.0        NaN       NaN